### ISSUE TITLE
Setting jenkins resource spec.master.securityContext causes operator to fail

### ISSUE THREAD

**Issue by paulczar** [redhat-developer/jenkins-operator#46]
When I create a Jenkins resource via the OpenShift Operators GUI and set PVC settings and securityContext for fsGroup settings (jenkins seems to run as user 1001, so I need to set fsGroup to 1001) the operator crashes.

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  creationTimestamp: "2021-05-21T19:13:30Z"
  generation: 1
  managedFields:
  - apiVersion: jenkins.io/v1alpha2
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:master:
          .: {}
          f:securityContext:
            .: {}
            f:fsGroup: {}
            f:runAsNonRoot: {}
            f:runAsUser: {}
        f:persistentSpec:
          .: {}
          f:enabled: {}
          f:storageClassName: {}
          f:volumeSize: {}
    manager: Mozilla
    operation: Update
    time: "2021-05-21T19:13:30Z"
  - apiVersion: jenkins.io/v1alpha2
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:jenkinsAPISettings:
          .: {}
          f:authorizationStrategy: {}
        f:jnlpService: {}
        f:service: {}
        f:serviceAccount: {}
      f:status:
        .: {}
        f:conditions: {}
    manager: manager
    operation: Update
    time: "2021-05-21T19:13:30Z"
  name: example-fsgroup
  namespace: jenkins-operator
  resourceVersion: "147438"
  selfLink: /apis/jenkins.io/v1alpha2/namespaces/jenkins-operator/jenkins/example-fsgroup
  uid: 45316f08-c3e4-4b7e-a7a7-29998eccad1e
spec:
  master:
    securityContext:
      fsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
  persistentSpec:
    enabled: true
    storageClassName: gp2
    volumeSize: 10Gi
```

operator logs:

```
2021-05-21T19:19:41.398Z        DEBUG   controllers.Jenkins     Got a reconcialition request at: 2021-05-21 19:19:41.398629124 +0000 UTC m=+4.200366885 for Jenkins: example-fsgroup in namespace: jenkins-operator   {"jenkins": "jenkins-operator/example-fsgroup"}
2021-05-21T19:19:41.398Z        INFO    controllers.Jenkins     Jenkins instance correctly found: 45316f08-c3e4-4b7e-a7a7-29998eccad1e  {"jenkins": "jenkins-operator/example-fsgroup"}
E0521 19:19:41.398749       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 561 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1680000, 0xc0004f1b40)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1680000, 0xc0004f1b40)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/runtime/panic.go:969 +0x1b9
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).getCalculatedJenkinsMaster(0xc0004940f0, 0xc0003b6000, 0x175eac1, 0x7, 0xc000048016, 0x6f, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:635 +0x19a
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).getCalculatedSpec(0xc0004940f0, 0x1948080, 0xc0000c0208, 0xc000ac6000, 0x1950860, 0xc000ac1d60, 0xc000ac3501)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:502 +0x258
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).setDefaults(0xc0004940f0, 0x1948080, 0xc0000c0208, 0xc000ac6000, 0x1950860, 0xc000ac1d00, 0x0)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:472 +0x127
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).reconcile(0xc0004940f0, 0x1948080, 0xc0000c0208, 0xc000617850, 0x10, 0xc000617830, 0xf, 0xc000ac6000, 0xc000ac6000, 0x0, ...)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:267 +0x131
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).Reconcile(0xc0004940f0, 0xc000617850, 0x10, 0xc000617830, 0xf, 0xfa5c1baa, 0xc0004be900, 0xc00049b728, 0xc00049b710)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:144 +0x81b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000279080, 0x15f6ee0, 0xc0007228e0, 0xc0002eb200)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000279080, 0xc000255f00)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000279080)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00047c3e0)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00047c3e0, 0x3b9aca00, 0x0, 0xc000453c01, 0xc0003c8120)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc00047c3e0, 0x3b9aca00, 0xc0003c8120)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x32d
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 561 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1680000, 0xc0004f1b40)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/runtime/panic.go:969 +0x1b9
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).getCalculatedJenkinsMaster(0xc0004940f0, 0xc0003b6000, 0x175eac1, 0x7, 0xc000048016, 0x6f, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:635 +0x19a
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).getCalculatedSpec(0xc0004940f0, 0x1948080, 0xc0000c0208, 0xc000ac6000, 0x1950860, 0xc000ac1d60, 0xc000ac3501)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:502 +0x258
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).setDefaults(0xc0004940f0, 0x1948080, 0xc0000c0208, 0xc000ac6000, 0x1950860, 0xc000ac1d00, 0x0)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:472 +0x127
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).reconcile(0xc0004940f0, 0x1948080, 0xc0000c0208, 0xc000617850, 0x10, 0xc000617830, 0xf, 0xc000ac6000, 0xc000ac6000, 0x0, ...)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:267 +0x131
github.com/jenkinsci/jenkins-automation-operator/controllers.(*JenkinsReconciler).Reconcile(0xc0004940f0, 0xc000617850, 0x10, 0xc000617830, 0xf, 0xfa5c1baa, 0xc0004be900, 0xc00049b728, 0xc00049b710)
        /go/src/github.com/jenkinsci/kubernetes-operator/controllers/jenkins_controller.go:144 +0x81b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000279080, 0x15f6ee0, 0xc0007228e0, 0xc0002eb200)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000279080, 0xc000255f00)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000279080)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00047c3e0)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00047c3e0, 0x3b9aca00, 0x0, 0xc000453c01, 0xc0003c8120)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc00047c3e0, 0x3b9aca00, 0xc0003c8120)
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/src/github.com/jenkinsci/kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x32d
```

**Comment by akram** [comment]
@waveywaves can PTAL to this issue ?

**Comment by waveywaves** [comment]
This is now fixed in https://github.com/redhat-developer/jenkins-operator/commit/4d9b460ffd5d829bb2929a0cf660808b3efb5384
